"""
Reads the truth about a Business Component out of QAD's dependency jar.

WHY THIS IS THE FOUNDATION OF CASE 3

Cases 1 and 2 had to infer structure and were corrected by wire captures more
than once. Case 3 does not have to infer anything: QAD hands us a jar
containing generated Java for every BC in the app's dependency set, and `javap`
reads it exactly. Field names, Java types, method signatures and - critically -
WHICH SAVE PATHS EXIST all come from the compiled artifact rather than a model,
a document, or a naming rule.

THE ONE THING THIS MODULE EXISTS TO PREVENT (observed live 2026-08-14)

Standard, QAD-shipped BCs expose BOTH a plain create/update AND a
createWithConfirmation/updateWithConfirmation pair. Entity-builder BCs (the
ones this app generates) expose only the plain trio. The QAD Web UI typically
saves through the WithConfirmation path, so an extension that overrides only
create/update on a coded BC compiles, deploys, returns HTTP 200 - and NEVER
FIRES. AUX documented the same trap for its TypeScript rules
(aux_web_version/backend/sss/templates.py:13-17).

    PurchaseOrderHeaderBaseService  -> 3 WithConfirmation methods
    SalesOrderHeaderBaseService     -> 3
    ItemBaseService                 -> 0
    DigSmokeTestBaseService (ours)  -> 0

So the save-path set is READ PER TARGET, every time. Nothing here guesses.

Signatures differ by family too, and the difference is load-bearing:

    standard   void create(XxxDataSet)
    generated  void create(InputOutput<XxxDataSet>)

Requires a JDK on PATH (`jar`, `javap`). Verified against JDK 17.0.12.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field as dc_field
from pathlib import Path
from typing import Dict, List, Optional

from core.logging_setup import get_logger

logger = get_logger("adaptive.jar")


class JarInspectionError(RuntimeError):
    """The jar could not be read, or a class was not in it."""


# The lifecycle methods an extension may override. Anything else on a
# BaseService (getPurchaseOrderHeaderByKey, handleSupplierChange, ...) is
# business API, not a save path, and is deliberately out of scope.
LIFECYCLE_ROOTS = ("create", "update", "delete", "initialize", "fetch", "exists")

# Only these are worth guarding with a validation: they are the paths a save
# travels. initialize/fetch/exists are reads or defaults.
MUTATING_ROOTS = ("create", "update", "delete")


@dataclass(frozen=True)
class SavePath:
    """One overridable lifecycle method, exactly as compiled."""
    name: str                    # "create" / "createWithConfirmation"
    param_types: List[str]       # fully-qualified, generics intact
    returns: str
    throws: str
    root: str                    # "create" / "update" / ...
    with_confirmation: bool

    @property
    def mutating(self) -> bool:
        return self.root in MUTATING_ROOTS

    @property
    def takes_input_output(self) -> bool:
        """True when the DataSet arrives wrapped (generated BCs do this)."""
        return any(p.startswith("com.qad.ipc.dto.InputOutput<") for p in self.param_types)

    def signature(self) -> str:
        return f"{self.returns} {self.name}({', '.join(_simple(p) for p in self.param_types)})"


@dataclass(frozen=True)
class RecordField:
    """A field on the BC's record, as a real Java accessor pair."""
    name: str            # "remarks"
    getter: str          # "getRemarks"
    java_type: str       # "java.lang.String"
    has_setter: bool

    @property
    def simple_type(self) -> str:
        return _simple(self.java_type)


@dataclass
class BusinessComponent:
    """Everything an extension author needs, read from the jar."""
    name: str                       # "PurchaseOrderHeader"
    package: str                    # "com.qad.purchasing.purchaseorders"
    base_service: str               # fully-qualified
    data_set: Optional[str] = None
    record: Optional[str] = None
    accessor: Optional[str] = None  # "getTtPurchaseOrderHeader"
    save_paths: List[SavePath] = dc_field(default_factory=list)
    fields: List[RecordField] = dc_field(default_factory=list)

    @property
    def is_app_owned(self) -> bool:
        """Generated by this app (vs QAD-shipped). Only affects presentation."""
        return not self.package.startswith("com.qad.")

    @property
    def mutating_paths(self) -> List[SavePath]:
        return [p for p in self.save_paths if p.mutating]

    @property
    def has_confirmation_variants(self) -> bool:
        return any(p.with_confirmation for p in self.save_paths)

    def summary(self) -> Dict[str, object]:
        return {
            "name": self.name,
            "package": self.package,
            "base_service": self.base_service,
            "record": self.record,
            "accessor": self.accessor,
            "app_owned": self.is_app_owned,
            "has_confirmation_variants": self.has_confirmation_variants,
            "save_paths": [
                {"name": p.name, "root": p.root, "with_confirmation": p.with_confirmation,
                 "mutating": p.mutating, "takes_input_output": p.takes_input_output,
                 "signature": p.signature()}
                for p in self.save_paths
            ],
            "fields": [
                {"name": f.name, "getter": f.getter, "type": f.simple_type,
                 "java_type": f.java_type}
                for f in self.fields
            ],
        }


def _simple(java_type: str) -> str:
    """'java.lang.String' -> 'String', keeping generics and arrays readable."""
    def shorten(m: re.Match) -> str:
        return m.group(0).rsplit(".", 1)[-1]
    return re.sub(r"[A-Za-z_][\w.]*\.[A-Z]\w*", shorten, java_type)


def _run(args: List[str]) -> str:
    # Resolve through PATHEXT rather than passing a bare name: on Windows a
    # tool shipped as .cmd/.bat (Maven is) raises WinError 2 from subprocess
    # even though the same word works in a terminal. jar/javap are .exe today,
    # but a wrapper script would break this the same way.
    exe = shutil.which(args[0])
    if not exe:
        raise JarInspectionError(
            f"'{args[0]}' is not on PATH. Case 3 needs a JDK (17 verified). "
            f"Install one, or set JAVA_HOME and add its bin/ to PATH.")
    try:
        proc = subprocess.run([exe, *args[1:]], capture_output=True, text=True, timeout=120)
    except FileNotFoundError as exc:
        raise JarInspectionError(f"Could not execute {exe}: {exc}") from exc
    except subprocess.TimeoutExpired as exc:
        raise JarInspectionError(f"'{args[0]}' timed out after 120s") from exc
    if proc.returncode != 0:
        raise JarInspectionError(
            f"{args[0]} failed (exit {proc.returncode}): "
            f"{(proc.stderr or proc.stdout or '').strip()[:400]}")
    return proc.stdout


# ── listing ──────────────────────────────────────────────────────────────────
_BASE_SERVICE = re.compile(r"^(?P<path>[\w/]+)/(?P<name>\w+)BaseService\.class$")


def list_components(jar: Path) -> List[BusinessComponent]:
    """Every BC the jar exposes a BaseService for, sorted by name.

    Inner classes (Foo$Bar.class) are excluded: they are the generated method
    runners, not services.
    """
    jar = Path(jar)
    if not jar.is_file():
        raise JarInspectionError(f"No dependency jar at {jar}. Fetch it first (jef.dependency_jar).")

    out: List[BusinessComponent] = []
    for line in _run(["jar", "tf", str(jar)]).splitlines():
        line = line.strip()
        if "$" in line:
            continue
        m = _BASE_SERVICE.match(line)
        if not m:
            continue
        pkg = m.group("path").replace("/", ".")
        name = m.group("name")
        out.append(BusinessComponent(
            name=name, package=pkg, base_service=f"{pkg}.{name}BaseService"))
    out.sort(key=lambda c: (not c.is_app_owned, c.name))
    logger.info("[JAR] %d business components in %s", len(out), jar.name)
    return out


def find(jar: Path, bc_name: str) -> BusinessComponent:
    """Look a BC up by simple name, case-insensitively."""
    wanted = bc_name.strip().lower()
    matches = [c for c in list_components(jar) if c.name.lower() == wanted]
    if not matches:
        near = [c.name for c in list_components(jar) if wanted in c.name.lower()][:8]
        raise JarInspectionError(
            f"No BaseService for '{bc_name}' in the jar."
            + (f" Did you mean: {', '.join(near)}?" if near else
               " The app's dependency set may not include that module."))
    if len(matches) > 1:
        raise JarInspectionError(
            f"'{bc_name}' is ambiguous across packages: "
            + ", ".join(m.base_service for m in matches))
    return matches[0]


# ── inspection ───────────────────────────────────────────────────────────────
# javap prints one member per line, e.g.
#   public void create(com.qad...DataSet) throws com.qad.ipc.dto.BCExecutionError;
#   public com.yash...Record[] getTtDigSmokeTest();
_MEMBER = re.compile(
    r"^\s*public\s+(?:final\s+|static\s+|abstract\s+)*"
    r"(?P<returns>[\w.$]+(?:<.+?>)?(?:\[\])?)\s+"
    r"(?P<name>\w+)\((?P<params>.*?)\)"
    r"(?:\s+throws\s+(?P<throws>[\w.,\s$]+))?;\s*$"
)


def _split_params(raw: str) -> List[str]:
    """Split a javap parameter list, respecting generic commas."""
    out, depth, cur = [], 0, ""
    for ch in raw:
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def _members(jar: Path, fqcn: str) -> List[re.Match]:
    text = _run(["javap", "-cp", str(jar), fqcn])
    return [m for m in (_MEMBER.match(line) for line in text.splitlines()) if m]


def _save_paths(jar: Path, base_service: str) -> List[SavePath]:
    paths: List[SavePath] = []
    for m in _members(jar, base_service):
        name = m.group("name")
        root = next((r for r in LIFECYCLE_ROOTS
                     if name == r or name == f"{r}WithConfirmation"), None)
        if root is None:
            continue
        paths.append(SavePath(
            name=name,
            param_types=_split_params(m.group("params")),
            returns=m.group("returns"),
            throws=(m.group("throws") or "").strip(),
            root=root,
            with_confirmation=name.endswith("WithConfirmation"),
        ))
    # Stable, human-meaningful order: lifecycle order, plain before confirmation.
    paths.sort(key=lambda p: (LIFECYCLE_ROOTS.index(p.root), p.with_confirmation))
    return paths


def _dataset_and_accessor(jar: Path, data_set: str) -> tuple[Optional[str], Optional[str]]:
    """The record type and the getTt<BC>() accessor, read off the DataSet.

    Deliberately derived rather than assumed: embedded children created before
    the naming settled expose records named after the physical table
    (XxembeddedRecord), so a rule built on the BC name would be wrong.
    """
    for m in _members(jar, data_set):
        name, returns = m.group("name"), m.group("returns")
        if name.startswith("getTt") and returns.endswith("[]") and not m.group("params"):
            return returns[:-2], name
    return None, None


_ACCESSOR = re.compile(r"^get(?P<field>[A-Z]\w*)$")


def _fields(jar: Path, record: str) -> List[RecordField]:
    getters: Dict[str, str] = {}
    setters = set()
    for m in _members(jar, record):
        name, returns, params = m.group("name"), m.group("returns"), m.group("params")
        g = _ACCESSOR.match(name)
        if g and not params and returns != "void":
            getters[g.group("field")] = returns
        elif name.startswith("set") and params:
            setters.add(name[3:])
    out = [
        RecordField(
            name=f[0].lower() + f[1:],
            getter=f"get{f}",
            java_type=t,
            has_setter=f in setters,
        )
        for f, t in getters.items()
    ]
    out.sort(key=lambda f: f.name)
    return out


def inspect(jar: Path, bc_name: str) -> BusinessComponent:
    """Full picture of one BC: save paths, record, fields and types.

    This is what the Case 3 target-analysis stage renders, and what the class
    generator builds from.
    """
    jar = Path(jar)
    bc = find(jar, bc_name)
    bc.save_paths = _save_paths(jar, bc.base_service)
    if not bc.save_paths:
        raise JarInspectionError(
            f"{bc.base_service} exposes no lifecycle methods. It may not be an "
            f"extendable business component.")

    candidate = f"{bc.package}.{bc.name}DataSet"
    try:
        record, accessor = _dataset_and_accessor(jar, candidate)
        bc.data_set, bc.record, bc.accessor = candidate, record, accessor
    except JarInspectionError:
        # A BC whose DataSet is not name-derivable: recover it from the
        # signature we already read rather than giving up.
        for p in bc.save_paths:
            for t in p.param_types:
                inner = t[len("com.qad.ipc.dto.InputOutput<"):-1] \
                    if t.startswith("com.qad.ipc.dto.InputOutput<") else t
                if inner.endswith("DataSet"):
                    bc.data_set = inner
                    bc.record, bc.accessor = _dataset_and_accessor(jar, inner)
                    break
            if bc.data_set:
                break

    if bc.record:
        bc.fields = _fields(jar, bc.record)

    logger.info("[JAR] %s: %d save path(s), %d field(s), confirmation=%s",
                bc.name, len(bc.save_paths), len(bc.fields),
                bc.has_confirmation_variants)
    return bc


def toolchain_ready() -> tuple[bool, str]:
    """Is a JDK reachable? Reported, never assumed."""
    try:
        out = _run(["javap", "-version"]).strip()
        return True, f"javap {out}"
    except JarInspectionError as exc:
        return False, str(exc)
